Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "sonarqube-vm"
  config.vm.boot_timeout = 1000
  
  # Forward SonarQube ports
  config.vm.network "forwarded_port", guest: 9000, host: 9001  # Optional: if accessing raw port 9000
  config.vm.network "forwarded_port", guest: 80, host: 8081     # NGINX reverse proxy
  config.vm.network "private_network", ip: "192.168.56.12"
  
  # Resource allocation
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"  # 4GB RAM
    vb.cpus = 4
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    bash /vagrant/sonar-setup.sh
  SHELL
  
end