Vagrant.configure("2") do |config|

    # db01 - CentOS 7
    config.vm.define "db01" do |db01|
        db01.vm.box = "eurolinux-vagrant/centos-stream-9"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.43"
        db01.vm.provision "shell", inline: <<-SHELL
            yum install wget unzip mariadb-server -y
            systemctl enable mariadb
            systemctl start mariadb
          # additional commands
        SHELL
    end

    # web01 - Ubuntu 20.04
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.41"
      web01.vm.boot_timeout = 300
      web01.vm.provision "shell", inline: <<-SHELL
        sudo touch /etc/cloud/cloud-init.disabled
      SHELL
    end
  
    # web02 - Ubuntu 20.04
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64"
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.42"
      web02.vm.boot_timeout = 300
      web02.vm.provision "shell", inline: <<-SHELL
        sudo touch /etc/cloud/cloud-init.disabled
      SHELL
    end
  
end