pipeline{
    agent any
    tools{
        // get Maven Name from Jenkins > Manage Jenkins > Tools > Maven Installations
        // use same name here
        maven "MAVEN_3.9"
        // get JDK Name from Jenkins > Manage Jenkins > Tools > JDK Installations
        // use same name here
        jdk "JDK_21"
    }
    stages{
        stage("Fetch Code"){
            steps{
                echo "========Fetching Code========"
                git branch: 'atom', url: 'https://github.com/vikas9dev/vprofile-project.git'
            }
            post{
                always{
                    echo "========Fetch Code - always========"
                }
                success{
                    echo "========Fetch Code executed successfully========"
                }
                failure{
                    echo "========Fetch Code execution failed========"
                }
            }
        }
        stage("Build"){
            steps{
                echo "========Build========"
                sh 'mvn install -DskipTests'
            }
            post{
                always{
                    echo "========Build - always========"
                }
                success{
                    echo "========Build executed successfully========"
                    echo "Archiving Artifact"
                    archiveArtifacts artifacts: '**/*.war'
                }
                failure{
                    echo "========Build execution failed========"
                }
            }
        }
        stage("Unit Test"){
            steps{
                echo "========Unit Test========"
                sh 'mvn test'
            }
            post{
                always{
                    echo "========Unit Test - always========"
                }
                success{
                    echo "========Unit Test executed successfully========"
                }
                failure{
                    echo "========Unit Test execution failed========"
                }
            }
        }
        stage("Checkstyle Analysis"){
            steps{
                echo "========Checkstyle Analysis========"
                sh 'mvn checkstyle:checkstyle'
            }
            post{
                always{
                    echo "========Checkstyle Analysis - always========"
                }
                success{
                    echo "========Checkstyle Analysis executed successfully========"
                }
                failure{
                    echo "========Checkstyle Analysis execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}